services:
  kipferlcrew-web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kipferlcrew-web.rule=Host(`kipferlcrew.com`)"
      - "traefik.http.routers.kipferlcrew-web.entrypoints=websecure"
      - "traefik.http.routers.kipferlcrew-web.tls=true"
      - "traefik.http.routers.kipferlcrew-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.kipferlcrew-web.loadbalancer.server.port=3000"

networks:
  traefik_default:
    external: true
